"""Phase 4 entry point: ``python -m src.phase4.run``.

Runs the Phase 3 retrieval subsystem over the configured query set, joins the
human relevance judgments, computes the evaluation metrics and writes the Phase 4
artefact set. Phase 1, Phase 2 and Phase 3 are read, never rerun.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

from src.core.utils import read_csv_rows

from .config import Phase4Config, clean_managed_output, load_config, log_event, seed_everything, setup_logging
from .evaluator import EvaluationRun, evaluate_pipeline, probe_pipeline
from .pooling import pool_from_phase3_config
from .relevance import RelevanceStore
from .reporting import (
    EVALUATION_FIELDS,
    FINAL_FIELDS,
    PIPELINE_FIELDS,
    SUMMARY_FIELDS,
    evaluation_rows,
    final_summary_rows,
    gui_summary,
    pipeline_comparison_rows,
    summary_rows,
    write_csv,
)
from .runtime import Phase3Runtime, load_phase3_runtime
from .validation import build_checks, run_checks, snapshot_inputs, summarise

BANNER = "=" * 78


def _read_json(path: Path) -> Dict[str, Any]:
    if not path.is_file():
        return {}
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def _phase3_rows(config: Phase4Config) -> Dict[str, Dict[str, str]]:
    path = config.input_path("phase3_pipeline_comparison")
    if not path.is_file():
        return {}
    return {row.get("pipeline", ""): row for row in read_csv_rows(path)}


def _selected_pipeline(runtime: Phase3Runtime) -> str:
    path = runtime.config.out_path("final_pipeline_json")
    payload = _read_json(path)
    chosen = str(payload.get("final_pipeline", "") or "")
    return chosen or runtime.final_pipeline


def _output_paths(config: Phase4Config) -> List[Path]:
    return [
        config.out_path("evaluation_results_csv"),
        config.out_path("evaluation_summary_csv"),
        config.out_path("pipeline_final_comparison_csv"),
        config.out_path("final_summary_csv"),
        config.out_path("final_summary_json"),
        config.out_path("gui_summary_json"),
        config.relevance_judgments_path,
    ]


def _readme(config: Phase4Config, summary: Dict[str, Any], run: Optional[EvaluationRun]) -> str:
    judgments = summary["judgments"]
    phase4 = summary["phase4"]
    aggregate = phase4.get("macro", {})
    lines = [
        "# Phase 4 results — evaluation, relevance judgments and API/GUI data",
        "",
        "Generated by `python -m src.phase4.run`. Every number here was computed by",
        "`src.phase4` from the human judgments in `relevance_judgments.csv` and the",
        "ranking produced by the Phase 3 retrieval engine. Nothing is hand-entered.",
        "",
        "## Files",
        "",
        "| File | Content |",
        "|---|---|",
        "| `relevance_judgments.csv` | one row per judged (query, content unit) pair |",
        "| `evaluation_results.csv` | precision / recall / F1 / P@K / R@K per query |",
        "| `evaluation_summary.csv` | macro and micro aggregates, unit and document level |",
        "| `pipeline_final_comparison.csv` | Pipeline A vs Pipeline B, Table J |",
        "| `final_summary.csv` / `.json` | the project-level report |",
        "| `gui_summary.json` | exactly the payload the dashboard renders |",
        "| `validation_report.csv` | Phase 4 validation rules |",
        "",
        "## Relevance judgments",
        "",
        f"- Judge pool depth: **{judgments['pool_depth']}** retrieved units per query",
        f"- Pairs judged: **{judgments['pairs']}** "
        f"({judgments['relevant']} relevant, {judgments['not_relevant']} not relevant)",
        f"- Annotator: {judgments['annotator']}",
        f"- Method: {judgments['judgment_method']}",
        "",
        "Rubric:",
        "",
        "```",
        str(judgments.get("rubric", "")).strip(),
        "```",
        "",
        "A label is never derived from a similarity score. A metric computed from the",
        "same function it is meant to evaluate would not measure anything.",
        "",
        "## Headline result",
        "",
    ]
    if aggregate.get("f1") is None:
        lines += [
            "No metrics are available: no relevance labels have been recorded yet.",
            "Open **Evaluation → Relevance judgments** in the dashboard, or edit",
            "`relevance_judgments.csv`, then rerun `python -m src.phase4.run`.",
        ]
    else:
        lines += [
            f"- Macro precision: **{aggregate['precision']}**",
            f"- Macro recall: **{aggregate['recall']}** (pool-bounded, see below)",
            f"- Macro F1: **{aggregate['f1']}**",
            "",
            "### How to read the recall figure",
            "",
            str(phase4.get("note", "")),
        ]
    lines += [
        "",
        "## Reproducing",
        "",
        "```",
        "python -m src.phase4.run",
        "```",
        "",
        "The run is deterministic: the query set, the pooling depth and the Phase 3",
        "ranking are all fixed, and ties in Phase 3 are broken by `unit_id` ascending.",
        "",
    ]
    return "\n".join(lines)


def run(config_path: Optional[str] = None, verbose: bool = False) -> Dict[str, Any]:
    started = time.perf_counter()
    config = load_config(config_path)
    logger = setup_logging(config, verbose=verbose)
    seed_everything(config.random_seed)

    print(BANNER)
    print("PHASE 4 - evaluation, relevance judgments and GUI data")
    print(BANNER)

    baselines = snapshot_inputs(config)
    removed = clean_managed_output(config, logger=logger)
    if removed:
        log_event(logger, "INFO", "setup", f"removed {len(removed)} stale Phase 4 output(s)")

    # ---------------- Phase 3 runtime --------------------------------
    log_event(logger, "INFO", "setup", "loading the Phase 1 corpus and the Phase 3 index")
    runtime = load_phase3_runtime(logger=logger)
    selected = _selected_pipeline(runtime)
    log_event(logger, "INFO", "setup", f"Phase 3 selected pipeline: {selected}")

    phase1_validation = _read_json(config.input_path("phase1_validation"))
    phase2_summary = _read_json(config.input_path("phase2_summary"))
    phase3_summary = _read_json(config.input_path("phase3_summary"))

    # ---------------- judgments ---------------------------------------
    store = RelevanceStore.load(config.relevance_judgments_path)
    log_event(
        logger, "INFO", "judgments",
        f"loaded {len(store)} relevance judgment(s) from {config.relevance_judgments_path.name}"
        + (f" ({len(store.problems)} problem(s))" if store.problems else ""),
    )
    for problem in store.problems:
        log_event(logger, "WARNING", "judgments", problem)

    # ---------------- evaluation --------------------------------------
    queries = pool_from_phase3_config(runtime.config)
    print(f"\nQueries: {len(queries)} from the Phase 3 configuration")
    print(f"Judgment pool depth: {config.pool_depth}\n")

    requested: List[str] = list(config.get("evaluation.pipelines", [selected]) or [selected])
    if selected not in requested:
        requested.insert(0, selected)

    runs: Dict[str, EvaluationRun] = {}
    for key in requested:
        if key not in runtime.specs:
            log_event(logger, "WARNING", "evaluate", f"unknown pipeline '{key}', skipped")
            continue
        engine = runtime.engine(key)
        print(f"--- evaluating on {key} " + "-" * (46 - len(key)))
        runs[key] = evaluate_pipeline(engine, queries, store, config, logger=logger)
        run_ = runs[key]
        aggregate = run_.aggregates.get("judged_depth")
        print(
            f"    {len(run_.evaluated_queries())}/{len(run_.queries)} query/queries evaluated"
            + (
                f" | macro P={aggregate.macro['precision']} R={aggregate.macro['recall']} "
                f"F1={aggregate.macro['f1']}"
                if aggregate and aggregate.macro.get("f1") is not None
                else " | no metrics (no judgments for these queries)"
            )
        )
    print()

    # The runner-up is measured on retrieval statistics only. Its ranking comes
    # from a different index, so the judgments pooled on the selected pipeline
    # are not a fair pool for it, and scoring it against them would produce a
    # comparison that looks valid and is not.
    probes: Dict[str, Dict[str, object]] = {}
    for key in runtime.specs:
        if key in runs:
            continue
        probes[key] = probe_pipeline(runtime.engine(key), queries, logger=logger)
        log_event(
            logger, "INFO", "evaluate",
            f"{key}: {probes[key]['answered']}/{probes[key]['queries']} answered, "
            f"{probes[key]['total_units_returned']} unit(s) returned, "
            f"mean {probes[key]['mean_execution_time_ms']}ms "
            f"(retrieval statistics only; relevance metrics N/A)",
        )

    if selected not in runs and runs:
        selected = next(iter(runs))
        log_event(logger, "WARNING", "evaluate",
                  f"selected pipeline was not evaluated; reporting on '{selected}' instead")

    # ---------------- artefacts ---------------------------------------
    print("-" * 78)
    print("OUTPUTS")
    print("-" * 78)

    rows: List[Dict[str, Any]] = []
    for key in sorted(runs):
        rows.extend(evaluation_rows(runs[key]))
    written: List[Path] = []

    path = write_csv(config.out_path("evaluation_results_csv"), EVALUATION_FIELDS, rows)
    written.append(path)
    print(f"  {path.relative_to(config.project_root)}  ({len(rows)} row(s))")

    summary_table = summary_rows(runs, store, config)
    path = write_csv(config.out_path("evaluation_summary_csv"), SUMMARY_FIELDS, summary_table)
    written.append(path)
    print(f"  {path.relative_to(config.project_root)}  ({len(summary_table)} row(s))")

    pipeline_table = pipeline_comparison_rows(_phase3_rows(config), runs, selected, probes)
    path = write_csv(config.out_path("pipeline_final_comparison_csv"), PIPELINE_FIELDS, pipeline_table)
    written.append(path)
    print(f"  {path.relative_to(config.project_root)}  ({len(pipeline_table)} row(s))")

    final_table = final_summary_rows(
        phase1_validation, phase2_summary, phase3_summary, runs, store, selected
    )
    path = write_csv(config.out_path("final_summary_csv"), FINAL_FIELDS, final_table)
    written.append(path)
    print(f"  {path.relative_to(config.project_root)}  ({len(final_table)} row(s))")

    final_json: Dict[str, Any] = {
        "phase": 4,
        "generated_by": "python -m src.phase4.run",
        "elapsed_seconds": None,
        "selected_pipeline": selected,
        "inputs": {
            "phase3_config": str(config.input_path("phase3_config")),
            "phase3_index": str(config.input_path("phase3_index")),
            "relevance_judgments": str(config.relevance_judgments_path),
        },
        "judgments": {
            "pairs": len(store),
            "relevant": sum(1 for j in store.judgments.values() if j.is_relevant),
            "not_relevant": sum(1 for j in store.judgments.values() if not j.is_relevant),
            "pool_depth": config.pool_depth,
            "annotator": config.get("relevance.annotator"),
            "judgment_method": config.get("relevance.judgment_method"),
            "rubric": config.get("relevance.rubric"),
            "queries": store.coverage([q.get("id", "") for q in queries]),
        },
        "evaluation": {key: run_.as_json() for key, run_ in sorted(runs.items())},
        "runner_up_retrieval_statistics": probes,
        "queries": [
            {
                "query_id": q.get("id"),
                "query": q.get("query"),
                "query_type": q.get("type"),
                "description": q.get("description"),
                "expected_domain": q.get("expected_domain"),
            }
            for q in queries
        ],
    }
    path = config.out_path("final_summary_json")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(final_json, indent=2, ensure_ascii=False), encoding="utf-8")
    written.append(path)
    print(f"  {path.relative_to(config.project_root)}")

    gui = gui_summary(
        phase1_validation, phase2_summary, phase3_summary, runs, store, selected, config
    )
    path = config.out_path("gui_summary_json")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(gui, indent=2, ensure_ascii=False), encoding="utf-8")
    written.append(path)
    print(f"  {path.relative_to(config.project_root)}")

    readme_path = config.out_path("readme")
    readme_path.parent.mkdir(parents=True, exist_ok=True)
    readme_path.write_text(_readme(config, gui, runs.get(selected)), encoding="utf-8")
    written.append(readme_path)
    print(f"  {readme_path.relative_to(config.project_root)}")

    if store.problems is not None and not config.relevance_judgments_path.is_file():
        log_event(logger, "WARNING", "judgments",
                  "no judgment file yet; create one to enable the evaluation metrics")

    # ---------------- validation --------------------------------------
    print()
    print("-" * 78)
    print("VALIDATION")
    print("-" * 78)
    checks = build_checks(
        config=config,
        store=store,
        runs=runs,
        selected=selected,
        baselines=baselines,
        output_files=_output_paths(config) + [readme_path],
    )
    results = run_checks(checks)
    validation_path = config.out_path("validation_report_csv")
    write_csv(
        validation_path,
        ("rule_id", "rule", "status", "detail", "evidence"),
        results,
    )
    for result in results:
        mark = "ok " if result["status"] == "PASS" else "FAIL"
        print(f"  [{mark}] {result['rule_id']}  {result['rule']}")
        print(f"         {result['detail']}")
    tally = summarise(results)
    log_event(
        logger, "INFO", "validation",
        f"{tally['passed']}/{tally['total']} rules passed",
    )
    final_json["elapsed_seconds"] = round(time.perf_counter() - started, 2)
    final_json["validation"] = tally
    path.write_text(json.dumps(final_json, indent=2, ensure_ascii=False), encoding="utf-8")

    print()
    print("-" * 78)
    print(f"Phase 4 complete in {final_json['elapsed_seconds']}s; "
          f"validation {tally['passed']}/{tally['total']}")
    print("-" * 78)
    return {"summary": final_json, "validation": tally, "runs": runs}


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Run the Phase 4 evaluation")
    parser.add_argument("--config", default=None, help="path to phase4_config.yaml")
    parser.add_argument("--verbose", action="store_true", help="debug level console logging")
    args = parser.parse_args(argv)
    result = run(config_path=args.config, verbose=args.verbose)
    return 0 if result["validation"]["failed"] == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
